[project]
name = "integration-sandbox"
version = "v1.0.5"
description = " A integration sandbox that provides mock endpoints to test against."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "deepdiff>=9.1.0",
    "faker>=40.36.0",
    "fastapi[standard]>=0.141.1",
    "httpx[cli]>=0.28.1",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = ["pytest>=9.1.1"]
